export const data = [
  {
    id: 1,
    img: require("../../assets/Future/img1.avif"),
    brand: "good smile company",
    name: "moderoid ikaruga",
    prodType: "model kit",
    price: 71,
    availability: "coming soon",
  },
  {
    id: 2,
    img: require("../../assets/Future/img2.avif"),
    brand: "yolopark",
    name: "transformers: bumblebee-shockwave",
    prodType: "model kit",
    price: 189.99,
    availability: "coming soon",
  },
  {
    id: 3,
    img: require("../../assets/Future/img3.avif"),
    brand: "yolopark",
    name: "meng model: eva-02 (production type)",
    prodType: "modle kit",
    price: 189.99,
    availability: "coming soon",
  },
  {
    id: 4,
    img: require("../../assets/Future/img4.avif"),
    brand: "eastern model",
    name: "1/9 iron man mark 43 (deluxe edition)",
    prodType: "model kit",
    price: 99.99,
    availability: "coming soon",
  },
  {
    id: 5,
    img: require("../../assets/Future/img5.avif"),
    brand: "plum",
    name: "as-5e3 leynos [player type] (renewal ver.)",
    prodType: "",
    price: 96,
    availability: "coming soon",
  },
  {
    id: 6,
    img: require("../../assets/Future/img6.avif"),
    brand: "delpi decal",
    name: "mg double x [manual ver.] holo",
    prodType: "accessory",
    price: 8,
    availability: "coming soon",
  },
];
