export const data = [
  {
    id: 1,
    img: require("../../assets/NewArrivals/img1.avif"),
    brand: "zero gravity",
    name: "moonlight judge",
    prodType: "model kit",
    price: 120,
    availability: "in stock",
  },
  {
    id: 2,
    img: require("../../assets/NewArrivals/img2.avif"),
    brand: "bandai",
    name: "hguc 003 zaku iii custom",
    prodType: "model kit",
    price: 19.99,
    availability: "in stock",
  },
  {
    id: 3,
    img: require("../../assets/NewArrivals/img3.avif"),
    brand: "bandai",
    name: "hgwfm 05 dilanza (standard type/lauda's dilanza)",
    prodType: "model kit",
    price: 22,
    availability: "in stock",
  },
  {
    id: 4,
    img: require("../../assets/NewArrivals/img4.avif"),
    brand: "bandai",
    name: "hgwfm 06 chuchu's demi trainer",
    prodType: "model kit",
    price: 18,
    availability: "in stock",
  },
  {
    id: 5,
    img: require("../../assets/NewArrivals/img5.avif"),
    brand: "fortune meow",
    name: "rg hi-nu gundam gk",
    prodType: "model kit",
    price: 159.99,
    availability: "in stock",
  },
  {
    id: 6,
    img: require("../../assets/NewArrivals/img6.avif"),
    brand: "bandai",
    name: "macross zero hi-metal r - vf-0s phoenix (roy focker use)",
    prodType: "figure",
    price: 159.99,
    availability: "in stock",
  },
  {
    id: 7,
    img: require("../../assets/NewArrivals/img7.avif"),
    brand: "bandai",
    name: "robot spirits gat-x105 strike gundam ver. a.n.i.m.e.",
    prodType: "figure",
    price: 48,
    availability: "in stock",
  },
  {
    id: 8,
    img: require("../../assets/NewArrivals/img8.avif"),
    brand: "tamashii nations",
    name: "gundam universe gu-21 rx-78gp01-fb gundam zephyranthes full burnern",
    prodType: "figure",
    price: 25,
    availability: "in stock",
  },
  {
    id: 9,
    img: require("../../assets/NewArrivals/img9.avif"),
    brand: "tamashii nations",
    name: "gundam universe gu-22 oz-06ms leo",
    prodType: "figure",
    price: 25,
    availability: "in stock",
  },
  {
    id: 10,
    img: require("../../assets/NewArrivals/img10.avif"),
    brand: "delpi decal",
    name: "rg goldymarg-[normal]",
    prodType: "accessory",
    price: 3,
    availability: "in stock",
  },
  {
    id: 11,
    img: require("../../assets/NewArrivals/img11.avif"),
    brand: "bandai",
    name: "30mm w-21 option parts set 10 (large propellant tank unit)",
    prodType: "model kit",
    price: 11,
    availability: "in stock",
  },
];
