export const data = [
  {
    id: 1,
    img: require("../../assets/Restocks/img1.avif"),
    brand: "bandai",
    name: "hbbgg 06 barbataurus",
    prodType: "model kit",
    price: 26,
    availability: "in stock",
  },
  {
    id: 2,
    img: require("../../assets/Restocks/img2.avif"),
    brand: "bandai",
    name: "mg msz-006 zeta gundam (ver 2.0)",
    prodType: "model kit",
    price: 61,
    availability: "in stock",
  },
  {
    id: 3,
    img: require("../../assets/Restocks/img3.avif"),
    brand: "dspiae",
    name: "st-a 3.0 single blade nipper",
    prodType: "tool",
    price: 39.95,
    availability: "in stock",
  },
  {
    id: 4,
    img: require("../../assets/Restocks/img4.avif"),
    brand: "dspiae",
    name: "at-sv omnidirectional spherical vise",
    prodType: "tool",
    price: 119.99,
    availability: "in stock",
  },
  {
    id: 5,
    img: require("../../assets/Restocks/img5.avif"),
    brand: "bandai",
    name: "mg gn-005 gundam virtue",
    prodType: "model kit",
    price: 94,
    availability: "in stock",
  },
  {
    id: 6,
    img: require("../../assets/Restocks/img6.avif"),
    brand: "bandai",
    name: "sdcs hello kitty/char's zaku ii",
    prodType: "model kit",
    price: 31,
    availability: "in stock",
  },
];
