export const data = [
  {
    id: 1,
    img: require("../../assets/Featured/img1.avif"),
    brand: "zippo",
    name: "lighter fluid",
    prodType: "paint",
    price: 3.99,
    availability: "in stock",
  },
  {
    id: 2,
    img: require("../../assets/Featured/img2.avif"),
    brand: "tamashii nations",
    name: "robot spirits side eva evangelion test type-01 + spear of cassius renewal color edition (3.0+1.0 thrice upon a time)",
    prodType: "figure",
    price: 75,
    availability: "in stock",
  },
  {
    id: 3,
    img: require("../../assets/Featured/img3.avif"),
    brand: "madworks",
    name: "mg-03 single blade nipper",
    prodType: "tool",
    price: 28,
    availability: "in stock",
  },
  {
    id: 4,
    img: require("../../assets/Featured/img4.avif"),
    brand: "fujimi",
    name: "evangelion louisiana crawfish (unit 02)",
    prodType: "model kit",
    price: 55,
    availability: "in stock",
  },
  {
    id: 5,
    img: require("../../assets/Featured/img5.avif"),
    brand: "studioG",
    name: "gpaint ultimate starter set 2.0",
    prodType: "paint",
    price: 60,
    availability: "in stock",
  },
  {
    id: 6,
    img: require("../../assets/Featured/img6.avif"),
    brand: "bandai",
    name: "hgaz 236 heavyarms",
    prodType: "model kit",
    price: 19.99,
    availability: "in stock",
  },
];
