export const data = [
  {
    id: 1,
    img: require("../../assets/Sale/img1.avif"),
    brand: "bandai",
    name: "mg rx-93 nu gundam ver.ka",
    prodType: "model kit",
    price: 79.99,
    availability: "in stock",
  },
  {
    id: 2,
    img: require("../../assets/Sale/img2.avif"),
    brand: "studioG",
    name: "gpaint ultimate starter set 2.0",
    prodType: "paint",
    price: 60,
    availability: "in stock",
  },
  {
    id: 3,
    img: require("../../assets/Sale/img3.avif"),
    brand: "bandai",
    name: "mg gundam deathscythe hell ew",
    prodType: "model kit",
    price: 49.99,
    availability: "in stock",
  },
  {
    id: 4,
    img: require("../../assets/Sale/img4.avif"),
    brand: "bandai",
    name: "mg epyon ew",
    prodType: "model kit",
    price: 55,
    availability: "in stock",
  },
  {
    id: 5,
    img: require("../../assets/Sale/img5.avif"),
    brand: "bandai",
    name: "hgibo 033 gundam barbatos lupus rex",
    prodType: "model kit",
    price: 14.99,
    availability: "in stock",
  },
  {
    id: 6,
    img: require("../../assets/Sale/img6.avif"),
    brand: "bandai",
    name: "hgac 174 wing gundam zero",
    prodType: "model kit",
    price: 16.99,
    availability: "in stock",
  },
];
