export const data = [
  {
    id: 1,
    img: require("../../assets/NewArrivals/img1.avif"),
    brand: "zero gravity",
    name: "moonlight judge",
    prodType: "model kit",
    price: 120,
    availability: "in stock",
  },
  {
    id: 2,
    img: require("../../assets/NewArrivals/img2.avif"),
    brand: "bandai",
    name: "hguc 003 zaku iii custom",
    prodType: "model kit",
    price: 19.99,
    availability: "in stock",
  },
  {
    id: 3,
    img: require("../../assets/NewArrivals/img3.avif"),
    brand: "bandai",
    name: "hgwfm 05 dilanza (standard type/lauda's dilanza)",
    prodType: "model kit",
    price: 22,
    availability: "in stock",
  },
  {
    id: 4,
    img: require("../../assets/NewArrivals/img4.avif"),
    brand: "bandai",
    name: "hgwfm 06 chuchu's demi trainer",
    prodType: "model kit",
    price: 18,
    availability: "in stock",
  },
  {
    id: 5,
    img: require("../../assets/NewArrivals/img5.avif"),
    brand: "fortune meow",
    name: "rg hi-nu gundam gk",
    prodType: "model kit",
    price: 159.99,
    availability: "in stock",
  },
  {
    id: 6,
    img: require("../../assets/NewArrivals/img5.avif"),
    brand: "fortune meow",
    name: "rg hi-nu gundam gk",
    prodType: "model kit",
    price: 159.99,
    availability: "in stock",
  },
];
